# Site settings

project:
    name: "TwoStream <sup>{{ Beta }}</sup>"
    tagline: Two-way communication between Laravel and the Client
    github: "https://github.com/CupOfTea696/TwoStream/"
    package: "cupoftea/twostream"
navigation:
  - name: Documentation
    link: "docs"
  - name: API
    link: "docs/api"
url: "http://twostream.cupoftea.io"
twitter_username: CupOfTea696
github_username:  CupOfTea696

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ['with_toc_data']
highlighter: pygments
pygments_options: ['startinline']
