# Site settings

project:
    name: "TwoStream <sup>{{ Beta }}</sup>"
    alt_name: "TwoStream"
    tagline: Two-way communication between Laravel and the Client
    author: "CupOfTea696"
    github: "https://github.com/CupOfTea696/TwoStream/"
    package: "cupoftea/twostream"
navigation:
  - name: Documentation
    url: "docs"
    navigation:
      - name: Getting Started
        type: category
      - name: Installation
        type: page
        url: "installation"
      - name: Configuration
        type: page
        url: "configuration"
      - name: Running TwoStream
        type: page
        url: "server"
      - name: The Basics
        type: category
      - name: Routing
        type: page
        url: "routing"
      - name: Controllers
        type: page
        url: "controllers"
      - name: Services
        type: category
  - name: API
    url: "docs/api"
url: "http://twostream.cupoftea.io"
twitter_username: CupOfTea696
github_username:  CupOfTea696

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'with_toc_data', 'html_toc', 'strikethrough', 'autolink', 'tables', 'footnotes', 'underline']
highlighter: pygments
pygments_options: ['startinline']
gems:
  - jekyll-assets
  - nokogiri
  - octopress-minify-html
assets:
  dirname: assets
  base_url: assets/
  cachebust: soft
  js_compressor: uglifier
  css_compressor: sass
  gzip: [ text/css, application/javascript ]
  sources:
    - _assets
